name: Pull Requests
on: [pull_request]

jobs:
  master:
    runs-on: ubuntu-latest
    name: Assert origin/master
    steps:

      - name: Comment
        uses: actions/github-script@v3
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'test'
                })
